name: PR Deploy
on:
  pull_request_target:
    branches:
      - dev

jobs:
  deploy-pr-for-testing:
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.preview-url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to branch
        uses: actions/checkout@v4
      - id: deploy
        name: Pull Request Deploy
        uses: hngprojects/pr-deploy@dev
        with:
          server_host: ${{ secrets.HOST }}
          server_username: ${{ secrets.USERNAME }}
          server_password: ${{ secrets.PASSWORD }}
          comment: false
          context: .
          dockerfile: Dockerfile
          exposed_port: 5000
          github_token: ${{ secrets.GITHUB_TOKEN }}
